version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8  # Base Docker image for the job

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout  # Check out the source code
      
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true

      - run:
          name: Build Docker Image
          command: |
            docker build -t my-app:latest .


workflows:
  version: 2
  build-and-push:
    jobs:
      - build