apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  selector:
    matchLabels:
      app: node
  replicas: 1 # specifies the number of instances
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: farhanluckali/node-helloworld:l234
        ports:
        - containerPort: 8080
