# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build and Deploy to GKE

on:
  workflow_dispatch: # Allows manual triggering of the workflow


env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: cluster-1    # Add your cluster name here.
  GKE_REGION: us-east1
  IMAGE: docker-basic
  GAR_LOCATION: ${{env.GKE_REGION}}-docker.pkg.dev/${{ secrets.GKE_PROJECT }}/demo/

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - id: "auth"
      uses: "google-github-actions/auth@v1"
      with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"
    - name: "Set up Cloud SDK"
      uses: "google-github-actions/setup-gcloud@v1"

    - name: "Use gcloud CLI"
      run: "gcloud info"
    - name: "Docker auth"
      run: |-
          gcloud auth configure-docker ${{ env.GKE_REGION }}-docker.pkg.dev --quiet
    - name: Build image
      run: docker build . --file DOCKERFILE_LOCATION --tag ${{ env.GAR_LOCATION }}
      working-directory: WORKING_DIRECTORY

    - name: Push image
      run: docker push ${{ env.GAR_LOCATION }}
  
