name: Test Secret Vars Builder (Comma-Separated)

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment Name (used in file name)'
        required: true
        default: 'sandbox'
      secretPrefix:
        description: 'Prefix for secrets (e.g. NGENIUS_INTEGRATOR_SANDBOX)'
        required: true

      secretKeys:
        description: 'Comma-separated secret keys (e.g. SECRET_KEY,MONGO_URI)'
        required: true
        type: string

jobs:
  build-vars:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate YAML File from Secrets
        run: |
          mkdir -p test/overrides

          secrets_yaml=""
          IFS=',' read -ra KEYS <<< "${{ github.event.inputs.secretKeys }}"
          for key in "${KEYS[@]}"; do
            paramName="${{ github.event.inputs.secretPrefix }}_${key}"
            val="arn:aws:ssm:us-east-1:980136594430:parameter/${paramName}"
            secrets_yaml="${secrets_yaml}
            - key: \"$key\"
              val: \"$val\""
          done

          cat <<EOF > test/overrides/${{ github.event.inputs.env }}-secrets.yml
          vars:${secrets_yaml}
          EOF

          echo "✅ Generated File:"
          cat test/overrides/${{ github.event.inputs.env }}-secrets.yml


