name: Test Secret Vars Builder (Comma-Separated)

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment Name (used in file name)'
        required: true
        default: 'sandbox'

      secretsList:
        description: 'Comma-separated SSM parameter names (e.g. KEY1,KEY2)'
        required: true
        type: string

jobs:
  build-vars:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate YAML File from Secrets
        run: |
          mkdir -p test/overrides

          secrets_yaml=""
          IFS=',' read -ra PARAMS <<< "${{ github.event.inputs.secretsList }}"
          for param in "${PARAMS[@]}"; do
            key=$(echo "$param" | awk -F '_' '{print $(NF)}')
            val="arn:aws:ssm:us-east-1:980136594430:parameter/${param}"
            secrets_yaml="${secrets_yaml}
          - key: \"$key\"
            val: \"$val\""
          done

          cat <<EOF > test/overrides/${{ github.event.inputs.env }}-secrets.yml
          vars:${secrets_yaml}
          EOF

          echo "✅ Generated File:"
          cat test/overrides/${{ github.event.inputs.env }}-secrets.yml


