name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            farhanluckali/node-helloworld:latest
            farhanluckali/node-helloworld:${GITHUB_SHA}

  image-tag-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Helm Values Repository
      uses: actions/checkout@v3
      with:
        repository: farhanaliali/argocd-demo  # Replace with the Helm values repository
        token: ${{ secrets.PAT }}
        path: helm-repo  # Clone into a separate folder
    - name: Update values.yaml File
      run: |
        sed -i "s/tag: .*/tag: ${GITHUB_SHA}/" helm-repo/helm-example/values.yaml

    - name: Commit and Push Updated Helm Values
      working-directory: helm-repo
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add helm-example/values.yaml
        git commit -m "Update Helm values.yaml with tag ${ GITHUB_SHA }"
        git push origin master
