name: Trigger Jenkins Seed Job

on:
  workflow_dispatch:
    inputs:
      folderName:
        description: 'Folder Name'
        required: true
        type: choice
        options: [DEV, STAGE, PROD]

      namespace:
        description: 'Kubernetes Namespace'
        required: true
        type: choice
        options: [tapapps, teamx, devtools]

      gitRepoUrl:
        description: 'Git Repository URL'
        required: true

      gitBranch:
        description: 'Git Branch'
        required: true
        default: main

      gitCredsId:
        description: 'Jenkins Git Credential ID'
        required: true
        default: github-token

jobs:
  stage-prod-deploy:
    name: Trigger Jenkins (Stage/Prod)
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.folderName != 'DEV' }}
    environment: ${{ github.event.inputs.folderName == 'STAGE' && 'stage' || 'production' }}

    steps:
      - name: Preview Inputs (Before Approval)
        run: |
          echo "### 🚀 Jenkins Deployment Preview" >> $GITHUB_STEP_SUMMARY
          echo "**Folder Name:** ${{ github.event.inputs.folderName }}" >> $GITHUB_STEP_SUMMARY
          echo "**Namespace:** ${{ github.event.inputs.namespace }}" >> $GITHUB_STEP_SUMMARY
          echo "**Git Repository URL:** ${{ github.event.inputs.gitRepoUrl }}" >> $GITHUB_STEP_SUMMARY
          echo "**Git Branch:** ${{ github.event.inputs.gitBranch }}" >> $GITHUB_STEP_SUMMARY
          echo "**Git Credentials ID:** ${{ github.event.inputs.gitCredsId }}" >> $GITHUB_STEP_SUMMARY

      - name: Trigger Jenkins Seed Job
        run: |
          curl -X POST "https://jenkins.demo-k8s.cloudns.ph/job/seed-dsl-job/buildWithParameters" \
            --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
            --insecure \
            --data-urlencode "FOLDER_NAME=${{ github.event.inputs.folderName }}" \
            --data-urlencode "NAMESPACE=${{ github.event.inputs.namespace }}" \
            --data-urlencode "GIT_REPO_URL=${{ github.event.inputs.gitRepoUrl }}" \
            --data-urlencode "GIT_BRANCH=${{ github.event.inputs.gitBranch }}" \
            --data-urlencode "GIT_CREDS_ID=${{ github.event.inputs.gitCredsId }}"

  dev-deploy:
    name: Trigger Jenkins (Dev)
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.folderName == 'DEV' }}

    steps:
      - name: Trigger Jenkins Seed Job
        run: |
          curl -X POST "https://jenkins.demo-k8s.cloudns.ph/job/seed-dsl-job/buildWithParameters" \
            --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
            --insecure \
            --data-urlencode "FOLDER_NAME=${{ github.event.inputs.folderName }}" \
            --data-urlencode "NAMESPACE=${{ github.event.inputs.namespace }}" \
            --data-urlencode "GIT_REPO_URL=${{ github.event.inputs.gitRepoUrl }}" \
            --data-urlencode "GIT_BRANCH=${{ github.event.inputs.gitBranch }}" \
            --data-urlencode "GIT_CREDS_ID=${{ github.event.inputs.gitCredsId }}"
